<?xml version="1.0" encoding="utf-8"?>
  
   <Database Name="AirlineWeb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ISENMURATI\SQL2012;Initial Catalog=AirlineWeb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AirlineWebConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Passangers" Member="Passangers">
    <Type Name="Passanger">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>